/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityLoader: typeof import('./components/common/ActivityLoader.vue')['default']
    AdminDashboardFilter: typeof import('./components/AdminDashboard/AdminDashboardFilter.vue')['default']
    AppBar: typeof import('./components/AppBar/AppBar.vue')['default']
    AttendanceTable: typeof import('./components/AdminDashboard/AttendanceTable.vue')['default']
    Calendar: typeof import('./components/Calendar/Calendar.vue')['default']
    DynamicForm: typeof import('./components/DynamicForm/DynamicForm.vue')['default']
    Form: typeof import('./components/Form/Form.vue')['default']
    FormBuilder: typeof import('./components/DynamicForm/FormBuilder.vue')['default']
    FullCalender: typeof import('./components/Calendar/FullCalender.vue')['default']
    Functions: typeof import('./components/Test/Functions.vue')['default']
    LoginForm: typeof import('./components/Login/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleCalendar: typeof import('./components/Schedule/ScheduleCalendar.vue')['default']
    SharedTable: typeof import('./components/TableRecords/SharedTable.vue')['default']
    TotalHoursDashboard: typeof import('./components/AdminDashboard/TotalHoursDashboard.vue')['default']
  }
}
